first:
  datasource:
    url: jdbc:h2:mem:first
    username: pjd
    password:
second:
  datasource:
    url:  jdbc:mysql://127.0.1.1:3306/dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: mysql
    password: 666
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8089
