-- 学生课程表
CREATE TABLE `STUDENTS` (ID INT IDENTITY, NAME VARCHAR(64), CREATETIME TIMESTAMP, UPDATETIME TIMESTAMP);
CREATE TABLE `COURSES` (ID INT IDENTITY, NAME VARCHAR(64), CREATETIME TIMESTAMP, UPDATETIME TIMESTAMP);
CREATE TABLE `COURSES_STUDENTS_RELATION` (ID INT IDENTITY, COURSES_ID INT, STUDENTS_ID INT, CREATETIME TIMESTAMP, UPDATETIME TIMESTAMP);
-- 简单测试
CREATE TABLE `FIRST` (ID INT IDENTITY, USERNAME VARCHAR(64));
CREATE TABLE `SECOND` (ID INT IDENTITY, JOB VARCHAR(64));