spring:
  application:
    name: web_play
  thymeleaf:
    cache: false # 是否开启缓存
    check-template: true # 检查模板是否存在
    prefix: classpath:/thymeleaf/
    servlet:
      content-type: text/html
    suffix: .html # 模板文件后缀
    encoding: utf-8 # 模本文件编码
    check-template-location: true # 检查模板位置是否存在
  freemarker:
    allow-request-override: false # 是否可以覆盖controller中的同名项
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false # 是否将HttpServlvetRquest中属性添加到Model中
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/freemarker/
  http:
    encoding:
      force-response: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
server:
  port: 80
  tomcat:
    max-swallow-size: 100MB #重要的一行，修改tomcat的吞吐量

breakpoint:
  upload:
    dir: D:/data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880