spring:
  application:
    name: web_play
  thymeleaf:
    cache: false # 是否开启缓存
    check-template: true # 检查模板是否存在
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html # 模板文件后缀
    encoding: utf-8 # 模本文件编码
    check-template-location: true # 检查模板位置是否存在
  freemarker:
    allow-request-override: false # 是否可以覆盖controller中的同名项
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false # 是否将HttpServlvetRquest中属性添加到Model中
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/freemarker/
  http:
    encoding:
      force-response: true